### ISSUE TITLE
Add Cake Addin to Website

### ISSUE THREAD

**Issue by gep13** [vCipher/Cake.HgVersion#7]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by phantomtypist** [comment]
@gep13 @vCipher @Jericho would you be willing to pass the torch on to me with this and also your [HgVersion](https://github.com/vCipher/HgVersion) repo?

**Comment by gep13** [comment]
This is now completed automatically by Cake.AddinDiscoverer, and doesn't need to be done manually.
